version: '3'
services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "ms-user"
    networks:
      - java-user-email
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - java-user-email

networks:
  java-user-email:
    external: true